Doc 15
desenho2019-1/docs pull request #12
Opened 2019-05-05 18:32 UTC by mbslet

## Issue #
#47

## Description
this pull request contains modifications to the prototype, introspection, mental map, rich picture and brainstorming documents: 
* Prototype description
* Added introspection reference
* Added brainstorming reference 
* Added mental map reference
* Added introduction of Mental Map
* Added introduction of Rich Picture
* Added describe of Rich Picture
* Added references of Rich Picture
* Added introduction and reference of Prototype

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2019-05-06 17:34 UTC, aleronupe requested changes

2019-05-06 17:34 UTC, aleronupe commented on docs/requisitos/elicitacao/brainstorming.md
>  ## Introdução
It would be better to have an introduction that describes what is a brainstorming

2019-05-06 17:34 UTC, aleronupe commented on docs/requisitos/elicitacao/brainstorming.md
> +### Referências
Put a reference from where you were guided to describe what is a brainstorming process. Also, this link does not describe the material used to be based on.

2019-05-06 17:34 UTC, aleronupe commented on docs/requisitos/elicitacao/prototipo.md
> +## Introdução
A More founded description of what is a protoype at modelling context would be better to understand the file. Use the point of view of someone that never developed and whant to know what does it means.

2019-05-06 18:03 UTC, victorhdcoelho commented
Pr's name is wrong and have conflicts with master !
Pr's name must be write with "Name of issue" format.

2019-05-06 18:18 UTC, victorhdcoelho submitted a review, later dismissed
Fix conflicts with master!

2019-05-07 04:30 UTC, aleronupe requested changes
It only needs to have topics sorted by numbers, the other criteria are according to what was asked.

2019-05-08 04:21 UTC, aleronupe approved these changes

2019-05-08 14:17 UTC, gabibguedes requested changes

2019-05-08 14:17 UTC, gabibguedes commented on docs/requisitos/elicitacao/brainstorming.md
> +#### 3.4.1. Protótipo - Login/Cadastro do Autor
It's not the login prototype, is the flux to send a new translation request,it's written login in the beginning just to represent the action

2019-05-08 14:17 UTC, gabibguedes commented on docs/requisitos/elicitacao/brainstorming.md
> +#### 3.4.2. Protótipo - Login/Cadastro do Tradutor
This is wrong as well, it is the pages for translation, review and see the translations in progress

2019-05-08 14:17 UTC, gabibguedes commented on docs/requisitos/elicitacao/mapa_mental.md
> +* Vizualizar a nivel macro a ideia
Add space between the topics, it is breaking on mkdocs

2019-05-08 18:58 UTC, gabibguedes approved these changes
Amazing!

2019-05-08 19:03 UTC, merged