41 refactor static umls artifacts
desenho2019-1/docs pull request #13
Opened 2019-05-05 19:26 UTC by victorhdcoelho

## Issue #
41 Refactor Static UML artifacts

## Description
Refactor the static uml document adding references, introduction and a brief explanation of how works the diagram

## Types of changes
- [x] Documentation

## Checklist:
- [x] I have updated the documentation accordingly.

2019-05-05 19:47 UTC, mbslet approved these changes
Well done and complete. Good explanations.

2019-05-05 19:52 UTC, RomuloSouza approved these changes
It's ok

2019-05-06 04:15 UTC, aleronupe requested changes
The version of the actual artifacts is missing. Once the actual diagrams are **not** the first version to compose the file, older versions should be added, so this versioning would represents our _work flow_ through the project.

2019-05-08 04:47 UTC, aleronupe approved these changes

2019-05-08 04:47 UTC, merged