Refactor NFR file structure
desenho2019-1/docs pull request #18
Opened 2019-05-07 04:14 UTC by aleronupe

Refactor NFR file with introduction, references and static images of frameworks

## Issue #
#17 

## Description
This issue add the modelling of NFR frameworks of security, support, usability and Privacy

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

2019-05-07 14:15 UTC, victorhdcoelho submitted a review, later dismissed
The frame of some diagrams need my google drive's access to load. Because of that a need permission to that document on drive for get view of it. I advise you to extract image of that diagrams and upload at the git.

2019-05-08 13:44 UTC, gabibguedes requested changes

2019-05-08 13:44 UTC, gabibguedes commented on docs/requisitos/modelagem/nfr.md
>  <iframe frameborder="0" style="width:160%;height:400px;" src="https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1#G1MJrp5h0Ak-EyIoB_GbuJ2dNzD2Rnbodu"></iframe>
I can't see this image with drawio, it seems like I don't have permission. Try change the permission so it's public or download it to the repo.

2019-05-08 13:44 UTC, gabibguedes commented on docs/requisitos/modelagem/nfr.md
>  <iframe frameborder="0" style="width:200%;height:400px;" src="https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1#G160iv-Dl_g6iKoA6OzDitaviQzbkm-6mR"></iframe>
Can't see this image either.

2019-05-08 19:25 UTC, renan601 approved these changes

2019-05-08 19:26 UTC, gabibguedes approved these changes
Awesome

2019-05-08 19:27 UTC, merged